name: Update GDELT CSV

on:
  workflow_dispatch: # Manual trigger from GitHub UI
  schedule:
    - cron: "0 * * * *" # ⏰ Runs at minute 0 of every hour (UTC)

jobs:
  update-gdelt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run updateCsv.mjs
        run: node scripts/updateCsv.mjs

      - name: Commit updated CSV
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add gdelt-mirror.csv
          git commit -m "Update gdelt-mirror.csv" || echo "No changes to commit"
          git push
